#!/bin/bash
soumet job_post -t 120 -cm 1G -cpus 1 -q micro1@ -jn job_post_1A
soumet job_post -t 120 -cm 1G -cpus 1 -q micro1@ -jn job_post_1A
soumet job_post -t 120 -cm 1G -cpus 1 -q micro2@ -jn job_post_1B
soumet job_post -t 120 -cm 1G -cpus 1 -q micro2@ -jn job_post_1B
soumet job_post -t 120 -cm 1G -cpus 1 -q micro1@ -jn job_post_2A
soumet job_post -t 120 -cm 1G -cpus 1 -q micro1@ -jn job_post_2A
soumet job_post -t 120 -cm 1G -cpus 1 -q micro2@ -jn job_post_2B
soumet job_post -t 120 -cm 1G -cpus 1 -q micro2@ -jn job_post_2B
soumet job_post -t 120 -cm 1G -cpus 1 -q micro1@ -jn job_post_3A
soumet job_post -t 120 -cm 1G -cpus 1 -q micro1@ -jn job_post_3A
soumet job_post -t 120 -cm 1G -cpus 1 -q micro2@ -jn job_post_3B
soumet job_post -t 120 -cm 1G -cpus 1 -q micro2@ -jn job_post_3B
