#!/bin/bash
soumet job_modela -t 120 -cm 1G -mpi -cpus 12 -q micro12a@ -jn job_model1a
soumet job_modela -t 120 -cm 1G -mpi -cpus 12 -q micro12a@ -jn job_model2a
soumet job_modelb -t 120 -cm 1G -mpi -cpus 12 -q micro12b@ -jn job_model3b
soumet job_modelb -t 120 -cm 1G -mpi -cpus 12 -q micro12b@ -jn job_model4b
soumet job_post -t 120 -cm 1G -cpus 1 -q micro1@ -jn job_post_2
soumet job_post -t 120 -cm 1G -cpus 1 -q micro1@ -jn job_post_2
soumet job_post -t 120 -cm 1G -cpus 1 -q micro1@ -jn job_post_2
soumet job_post -t 120 -cm 1G -cpus 1 -q micro1@ -jn job_post_2
soumet job_post -t 120 -cm 1G -cpus 1 -q micro2@ -jn job_post_3
soumet job_post -t 120 -cm 1G -cpus 1 -q micro2@ -jn job_post_3
soumet job_post -t 120 -cm 1G -cpus 1 -q micro2@ -jn job_post_3
soumet job_post -t 120 -cm 1G -cpus 1 -q micro2@ -jn job_post_3
