
ifeq "$(BASE_ARCH)" "$(EC_ARCH)"
$(error FATAL: EC_ARCH is equal to BASE_ARCH, no compiler architecture is defined, ABORTING)
endif

$(info including Makefile for EC setup)
# this is for sites using the EC setup

CFLAGS =  -O 2
FCFLAGS = -O 2

CC=s.cc
# use s.f77 with IBM fortran compiler because of fixed format
ifeq (/xlf,$(findstring /xlf,$(EC_ARCH)))
 FC=s.f77
 MPIFC = s.f77 -mpi
else
 FC=s.f90
 MPIFC = s.f90 -mpi
endif
F90C=s.f90
MPICC = s.cc -mpi
MPIF90C = s.f90 -mpi

# end of EC setup

