#!/bin/bash
NewDir=0
BaseDir=100
((LastDir=BaseDir))
NewPath=$TMPDIR/bin:$TMPDIR/.path_cache_${BaseDir}
for i in $(echo $PATH | tr ':' '\n') 
do
  mkdir -p $TMPDIR/.path_cache_${BaseDir}
  ./link_files_in_dir $i $TMPDIR/.path_cache_${BaseDir}
  status=$?
  if ((status==2)) ; then
    NewPath=${NewPath}:$i
    if ((NewDir==0)) ; then
      ((BaseDir=BaseDir+1))
      ((NewDir=1))
    fi
  else
    if ((LastDir!=BaseDir)) ; then
      NewPath=${NewPath}:$TMPDIR/.path_cache_${BaseDir}
      ((LastDir=BaseDir))
    fi
    ((NewDir=0))
  fi
done
echo "INFO: NEW PATH will be"
echo "${NewPath}" | tr ':' '\n'
